baseURL = "https://nathanielwestveer.com/"
languageCode = "en-us"
title = "Nathaniel's Developer Blog"
theme = "zen"

[author]
  name = "Nathaniel Westveer"

[params]
  description = "The developer blog of Nathaniel Westveer. Exploring opinionated software design, VFX, Python, Flutter, and Hugo."
